using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Askyl.Dsm.WebHosting.SourceGenerators;

[Generator]
public class CloneGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Generate the attribute once for the assembly
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "GenerateCloneAttribute.g.cs",
            SourceText.From(@"// <auto-generated/>
namespace Askyl.Dsm.WebHosting.SourceGenerators
{
	[System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
	internal sealed class GenerateCloneAttribute : System.Attribute
	{
	}
}
", Encoding.UTF8)));

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m.Node is not null);

        context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(source, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        => node is ClassDeclarationSyntax classDeclaration && classDeclaration.AttributeLists.Count > 0;

    private static (ClassDeclarationSyntax? Node, SemanticModel? Model) GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        return classDeclaration.AttributeLists
            .SelectMany(al => al.Attributes)
            .Select(attr => context.SemanticModel.GetSymbolInfo(attr).Symbol)
            .OfType<IMethodSymbol>()
            .Any(symbol => symbol.ContainingType.Name == "GenerateCloneAttribute")
            ? (classDeclaration, context.SemanticModel)
            : (null, null);
    }

    private static void Execute((ClassDeclarationSyntax? Node, SemanticModel? Model) data, SourceProductionContext context)
    {
        var classDeclaration = data.Node!;
        var semanticModel = data.Model!;

        var namespaceName = GetNamespace(classDeclaration);
        var className = classDeclaration.Identifier.Text;

        var properties = classDeclaration.Members.OfType<PropertyDeclarationSyntax>()
                                                 .Where(p => p.AccessorList?.Accessors.Any(a => a.IsKind(SyntaxKind.SetAccessorDeclaration) || a.IsKind(SyntaxKind.InitAccessorDeclaration)) == true)
                                                 .Select(p => (p, semanticModel.GetTypeInfo(p.Type).Type))
                                                 .ToList();

        var source = GenerateCloneMethod(namespaceName, className, properties, classDeclaration, context.CancellationToken);

        context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GetNamespace(ClassDeclarationSyntax classDeclaration)
    {
        var namespaceDeclaration = classDeclaration.Ancestors().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault();
        return namespaceDeclaration?.Name.ToString() ?? String.Empty;
    }

    private static string GenerateCloneMethod(string namespaceName, string className, List<(PropertyDeclarationSyntax Property, ITypeSymbol? TypeSymbol)> properties, ClassDeclarationSyntax classDeclaration, CancellationToken cancellationToken)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("using Askyl.Dsm.WebHosting.Data.Patterns;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {className} : IGenericCloneable<{className}>");
        sb.AppendLine("{");
        sb.AppendLine($"\tpublic {className} Clone()");
        sb.AppendLine("\t\t=> new()");
        sb.AppendLine("\t\t{");

        foreach (var (property, typeSymbol) in properties)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var propertyName = property.Identifier.Text;
            var propertyType = property.Type.ToString();

            if (IsCloneableType(typeSymbol))
            {
                sb.AppendLine($"\t\t\t{propertyName} = this.{propertyName}?.Clone(),");
            }
            else if (IsListType(propertyType))
            {
                var elementSymbol = typeSymbol is INamedTypeSymbol namedType && namedType.TypeArguments.Length > 0
                    ? namedType.TypeArguments[0]
                    : typeSymbol;

                if (IsCloneableType(elementSymbol))
                {
                    sb.AppendLine($"\t\t\t{propertyName} = this.{propertyName}?.Select(item => item.Clone())?.ToList(),");
                }
                else
                {
                    sb.AppendLine($"\t\t\t{propertyName} = this.{propertyName} is null ? null : [.. this.{propertyName}],");
                }
            }
            else
            {
                sb.AppendLine($"\t\t\t{propertyName} = this.{propertyName},");
            }
        }

        sb.AppendLine("\t\t};");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool IsCloneableType(ITypeSymbol? typeSymbol)
        => typeSymbol?.GetAttributes().Any(attr => attr.AttributeClass?.Name == "GenerateCloneAttribute") == true;

    private static bool IsListType(string typeName)
        => typeName.StartsWith("List<") || typeName.StartsWith("IList<") || typeName.StartsWith("IEnumerable<");

    private static string GetListElementType(string listType)
    {
        var start = listType.IndexOf('<') + 1;
        var end = listType.LastIndexOf('>');
        return listType.Substring(start, end - start);
    }
}
