// <auto-generated/>
namespace Askyl.Dsm.WebHosting.SourceGenerators
;

[AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GenerateCloneAttribute : Attribute
{
}
